#!/bin/bash
# 
# @author Zeus Intuivo <zeus@intuivo.com>
#
#

sudo echo " Hi"

[ ! -d ~/.ssh/ ] && echo -e "\n  Error ~/.ssh/ does not exist \n "
#cd ~/
cd ~/.ssh/
#mkdir -p ~/.ssh/
#chmod 700 ~/.ssh/

KEYLIST=$(ls *.pub | sed 's/id_rsa.pub//' | sed 's/_rsa.pub//')

PROVIDED_USER=""
if [ ! -z "${1}" ] ;  then
    PROVIDED_USER="${1}"
else 
	echo " Error"
	echo " "
	echo " ssh_generatekeys username    "
	echo " "
	echo " expected"
	echo -e "\n Pick from key on the list: \n ${KEYLIST} \n" 
	echo " "
	exit 1
fi




OUTPUT_FOLDER=$(pwd)

[ ! -f ${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa ] && echo -e "\n  Error this key does not exist. Pick from key on the list: \n ${KEYLIST} \n" && exit 1
sudo cp ${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa ${OUTPUT_FOLDER}/id_rsa
chmod 400 ${OUTPUT_FOLDER}/id_rsa
sudo cp ${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa.pub ${OUTPUT_FOLDER}/id_rsa.pub
chmod 400 ${OUTPUT_FOLDER}/id_rsa.pub



# REF: https://www.shellhacks.com/regex-find-email-addresses-file-grep/
GET_EMAIL_FROM_PUB_KEY=$(cat ${OUTPUT_FOLDER}/id_rsa.pub | grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b")
GET_USERNAME_FROM_EMAIL=$(echo "${GET_EMAIL_FROM_PUB_KEY}" | grep -E -o "\b[A-Za-z0-9._%+-]+\b" | head -1 )

USERNAME="${GET_USERNAME_FROM_EMAIL}"

#ssh -vT git@github.com
TEST_GIT=$(ssh -T git@github.com 2>&1) #  Pipe both stderr and  stdout to variable
echo "${TEST_GIT}"
[[ "${TEST_GIT}" ==  *"Permission denied"* ]] && xclip -sel clip < ${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa.pub  && echo "------ Key Needs to be added in WebPAGE. Copied to CLipboard"
[[ "${TEST_GIT}" ==  *"successfully authenticated"* ]] && GET_USERNAME_FROM_GREETING=$(echo "${TEST_GIT%\!*}" | sed -e 's/Hi //') && USERNAME="${GET_USERNAME_FROM_GREETING}"



git config --global user.email "${GET_EMAIL_FROM_PUB_KEY}"
git config --global user.name "${USERNAME}"

git config -l 

echo " "
echo "ls -la ${OUTPUT_FOLDER}"
echo " "
ls -la ${OUTPUT_FOLDER}